<a href="https://colab.research.google.com/github/srijamaradana/MACHINE-LEARNING-ASSIGNMENTS/blob/main/Taxi_Fare_Prediction_(Chicago_Taxi_Trips).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://data.cityofchicago.org/resource/wrvz-psew.csv?$limit=1000"

df = pd.read_csv(url)

print(df.shape)

(1000, 23)

In [3]:
df.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,fd4f3f628496b076e06a91e6933bb12489e1c65a,41ba5cfc7d59a833c94ed0b59fcc8a5f3aa5ca1b291325...,2023-12-31T23:45:00.000,2024-01-01T00:00:00.000,427,1.28,NaN,NaN,24.0,8.0,...,0.0,11.22,Mobile,City Service,41.901207,-87.676356,POINT (-87.6763559892 41.9012069941),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
1,e152a52aceb5d600a63311bbfe9b23ccdb9592dd,b56b31883524426035c290bfdbe4e038baccc814842c10...,2023-12-31T23:45:00.000,2024-01-01T00:00:00.000,894,6.81,NaN,NaN,8.0,3.0,...,0.0,19.32,Mobile,Sun Taxi,41.899602,-87.633308,POINT (-87.6333080367 41.899602111),41.965812,-87.655879,POINT (-87.6558787862 41.96581197)
2,2433c5101820db89c701ad242c7343d029f01bd2,6b8bec9d4caa49041a1f5d31240ff8fa2e4c571aec8921...,2023-12-31T23:45:00.000,2024-01-01T00:15:00.000,1478,2.03,NaN,NaN,28.0,8.0,...,0.0,13.17,Mobile,City Service,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
3,c5ad9b572bff9d5cb9a8cf0da173789f7910a835,c7a8a53874bbcdb11e70a488485e8bdd0bb8cc0de8f5d9...,2023-12-31T23:45:00.000,2023-12-31T23:45:00.000,7,0.00,NaN,NaN,28.0,28.0,...,0.0,30.50,Credit Card,Flash Cab,41.874005,-87.663518,POINT (-87.6635175498 41.874005383),41.874005,-87.663518,POINT (-87.6635175498 41.874005383)
4,7de7d6b1667cea33735670f88c50e9631e719f04,756721b3418247472431e2bd1022cc8ce0806af1b6b7df...,2023-12-31T23:45:00.000,2024-01-01T00:00:00.000,1138,12.08,NaN,NaN,56.0,24.0,...,7.0,43.75,Credit Card,Medallion Leasin,41.792592,-87.769615,POINT (-87.7696154528 41.7925923603),41.901207,-87.676356,POINT (-87.6763559892 41.9012069941)

In [4]:
print(df.columns.tolist())

['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp', 'trip_seconds', 'trip_miles', 'pickup_census_tract', 'dropoff_census_tract', 'pickup_community_area', 'dropoff_community_area', 'fare', 'tips', 'tolls', 'extras', 'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude', 'pickup_centroid_longitude', 'pickup_centroid_location', 'dropoff_centroid_latitude', 'dropoff_centroid_longitude', 'dropoff_centroid_location']

In [5]:
df = df[['trip_miles', 'trip_seconds', 'fare']]
df.head()

   trip_miles  trip_seconds   fare
0        1.28           427   9.00
1        6.81           894  17.30
2        2.03          1478  10.52
3        0.00             7  30.00
4       12.08          1138  31.25

In [6]:
df.isnull().sum()

trip_miles      0
trip_seconds    0
fare            1
dtype: int64

In [7]:
df = df.dropna()

df['trip_miles'] = pd.to_numeric(df['trip_miles'], errors='coerce')
df['trip_seconds'] = pd.to_numeric(df['trip_seconds'], errors='coerce')
df['fare'] = pd.to_numeric(df['fare'], errors='coerce')

df = df.dropna()

print(df.shape)

(999, 3)

In [8]:
X = df[['trip_miles', 'trip_seconds']]
y = df['fare']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [11]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[18.60844204 10.40385793 10.67560937 29.93725613 16.01692048  8.02306887
 11.95575877 44.29852291 33.88352366 10.45869092]

In [12]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE =", mean_absolute_error(y_test, y_pred))
print("R2 =", r2_score(y_test, y_pred))

MAE = 5.569872857683008
R2 = 0.6290647219723998

In [13]:
sample = [[5, 900]]

fare = model.predict(sample)

print("Predicted Fare =", fare[0])

Predicted Fare = 18.971844719117748

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(